import type {
  Junction,
  RiskTier,
  Officer,
  AuditEntry,
  FestivalEvent,
  Incident,
} from "@/lib/types";
import { tierFromScore } from "@/lib/utils";

export const TIER_META: Record<
  RiskTier,
  { label: string; color: string; tint: string; text: string; ring: string }
> = {
  high: {
    label: "High Risk",
    color: "#c62828",
    tint: "#fde6e6",
    text: "text-risk-high",
    ring: "ring-risk-high/30",
  },
  medium: {
    label: "Medium Risk",
    color: "#ef8a00",
    tint: "#fff4e0",
    text: "text-risk-med",
    ring: "ring-risk-med/30",
  },
  low: {
    label: "Low Risk",
    color: "#2e7d32",
    tint: "#e6f4e8",
    text: "text-risk-low",
    ring: "ring-risk-low/30",
  },
};

export function tierOf(j: { risk: number }): RiskTier {
  return tierFromScore(j.risk);
}

/** 22 real Nagpur junctions with curated living-risk data. */
export const JUNCTIONS: Junction[] = [
  {
    id: "sitabuldi",
    name: "Sitabuldi Main Square",
    nameMr: "सिटीबुल्दी",
    lat: 21.1496,
    lng: 79.086,
    zone: "Central",
    risk: 0.88,
    predicted: { t30: 0.91, t60: 0.85, t120: 0.79 },
    confidence: 0.92,
    manned: false,
    officersAssigned: 0,
    recommendedOfficers: 2,
    blackspot: true,
    signalized: true,
    hasCamera: true,
    waterlogged: false,
    density: 142,
    violations: { noHelmet: 38, tripleRide: 24, wrongWay: 12, redLight: 18, illegalPark: 31 },
    signal: { currentDelay: 48, recommendedDelay: 26, currentSplit: 0.5, recommendedSplit: 0.34 },
    factors: [
      { label: "Triple-riding surge", weight: 0.27, tone: "danger" },
      { label: "Monsoon rain · slick surface", weight: 0.21, tone: "info" },
      { label: "Market-hour density peak", weight: 0.19, tone: "warn" },
      { label: "Currently unmanned", weight: 0.18, tone: "danger" },
      { label: "Historic 2W–pedestrian conflicts", weight: 0.15, tone: "neutral" },
    ],
  },
  {
    id: "variety",
    name: "Variety Square (Lokmat)",
    nameMr: "व्हरायटी चौक",
    lat: 21.1455,
    lng: 79.0851,
    zone: "Central",
    risk: 0.82,
    predicted: { t30: 0.84, t60: 0.8, t120: 0.74 },
    confidence: 0.9,
    manned: true,
    officersAssigned: 1,
    recommendedOfficers: 2,
    blackspot: true,
    signalized: true,
    hasCamera: true,
    waterlogged: false,
    density: 128,
    violations: { noHelmet: 41, tripleRide: 19, wrongWay: 9, redLight: 22, illegalPark: 16 },
    signal: { currentDelay: 44, recommendedDelay: 24, currentSplit: 0.5, recommendedSplit: 0.36 },
    factors: [
      { label: "No-helmet rate 41%", weight: 0.26, tone: "danger" },
      { label: "Red-light jumping", weight: 0.22, tone: "danger" },
      { label: "Signal fixed-timing queue", weight: 0.18, tone: "warn" },
      { label: "Market-hub pedestrian mix", weight: 0.16, tone: "neutral" },
      { label: "Under-staffed (1 of 2)", weight: 0.18, tone: "danger" },
    ],
  },
  {
    id: "lic",
    name: "LIC Square",
    nameMr: "एलआयसी चौक",
    lat: 21.152,
    lng: 79.079,
    zone: "Central",
    risk: 0.76,
    predicted: { t30: 0.78, t60: 0.73, t120: 0.68 },
    confidence: 0.87,
    manned: false,
    officersAssigned: 0,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: true,
    hasCamera: true,
    waterlogged: false,
    density: 110,
    violations: { noHelmet: 29, tripleRide: 12, wrongWay: 14, redLight: 11, illegalPark: 9 },
    signal: { currentDelay: 39, recommendedDelay: 23, currentSplit: 0.5, recommendedSplit: 0.4 },
    factors: [
      { label: "Wrong-way movement", weight: 0.24, tone: "danger" },
      { label: "Office-corridor peak", weight: 0.21, tone: "warn" },
      { label: "Unmanned", weight: 0.2, tone: "danger" },
      { label: "Reduced visibility (dust)", weight: 0.16, tone: "info" },
      { label: "Bus stop conflict", weight: 0.19, tone: "neutral" },
    ],
  },
  {
    id: "medical",
    name: "Medical Square",
    nameMr: "मेडिकल चौक",
    lat: 21.1505,
    lng: 79.073,
    zone: "Central",
    risk: 0.79,
    predicted: { t30: 0.82, t60: 0.77, t120: 0.71 },
    confidence: 0.88,
    manned: true,
    officersAssigned: 1,
    recommendedOfficers: 2,
    blackspot: true,
    signalized: true,
    hasCamera: true,
    waterlogged: false,
    density: 118,
    violations: { noHelmet: 33, tripleRide: 16, wrongWay: 8, redLight: 14, illegalPark: 27 },
    signal: { currentDelay: 41, recommendedDelay: 24, currentSplit: 0.5, recommendedSplit: 0.38 },
    factors: [
      { label: "Ambulance corridor congestion", weight: 0.26, tone: "danger" },
      { label: "Illegal parking near OPD", weight: 0.22, tone: "warn" },
      { label: "Hospital proximity conflict", weight: 0.2, tone: "neutral" },
      { label: "Under-staffed (1 of 2)", weight: 0.18, tone: "danger" },
      { label: "Mixed 2W–auto weave", weight: 0.14, tone: "neutral" },
    ],
  },
  {
    id: "ajni",
    name: "Ajni Square",
    nameMr: "अजनी चौक",
    lat: 21.139,
    lng: 79.067,
    zone: "West",
    risk: 0.58,
    predicted: { t30: 0.61, t60: 0.57, t120: 0.53 },
    confidence: 0.83,
    manned: true,
    officersAssigned: 1,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: true,
    hasCamera: true,
    waterlogged: false,
    density: 86,
    violations: { noHelmet: 22, tripleRide: 8, wrongWay: 6, redLight: 9, illegalPark: 11 },
    signal: { currentDelay: 34, recommendedDelay: 22, currentSplit: 0.5, recommendedSplit: 0.42 },
    factors: [
      { label: "Rail-overbridge bottleneck", weight: 0.23, tone: "warn" },
      { label: "Office commute peak", weight: 0.2, tone: "warn" },
      { label: "Moderate no-helmet", weight: 0.17, tone: "neutral" },
      { label: "Signal fixed timing", weight: 0.15, tone: "info" },
      { label: "Adequate lighting", weight: 0.12, tone: "good" },
    ],
  },
  {
    id: "ramdaspeth",
    name: "Ramdaspeth",
    nameMr: "रामदासपeth",
    lat: 21.142,
    lng: 79.079,
    zone: "Central",
    risk: 0.54,
    predicted: { t30: 0.56, t60: 0.52, t120: 0.49 },
    confidence: 0.82,
    manned: false,
    officersAssigned: 0,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: true,
    hasCamera: false,
    waterlogged: false,
    density: 74,
    violations: { noHelmet: 18, tripleRide: 6, wrongWay: 5, redLight: 7, illegalPark: 13 },
    signal: { currentDelay: 31, recommendedDelay: 21, currentSplit: 0.5, recommendedSplit: 0.44 },
    factors: [
      { label: "Camera coverage gap", weight: 0.22, tone: "warn" },
      { label: "Unmanned", weight: 0.2, tone: "danger" },
      { label: "Commercial parking spill", weight: 0.19, tone: "warn" },
      { label: "Steady commuter flow", weight: 0.16, tone: "neutral" },
      { label: "Low conflict history", weight: 0.12, tone: "good" },
    ],
  },
  {
    id: "dharampeth",
    name: "Dharampeth",
    nameMr: "धर्मापeth",
    lat: 21.147,
    lng: 79.078,
    zone: "West",
    risk: 0.47,
    predicted: { t30: 0.49, t60: 0.45, t120: 0.43 },
    confidence: 0.8,
    manned: true,
    officersAssigned: 1,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: true,
    hasCamera: true,
    waterlogged: false,
    density: 68,
    violations: { noHelmet: 16, tripleRide: 5, wrongWay: 4, redLight: 6, illegalPark: 10 },
    signal: { currentDelay: 28, recommendedDelay: 19, currentSplit: 0.5, recommendedSplit: 0.46 },
    factors: [
      { label: "School-zone AM peak", weight: 0.21, tone: "warn" },
      { label: "Lane discipline fair", weight: 0.16, tone: "good" },
      { label: "Manned, steady flow", weight: 0.15, tone: "good" },
      { label: "Minor parking friction", weight: 0.13, tone: "neutral" },
      { label: "Good visibility", weight: 0.12, tone: "good" },
    ],
  },
  {
    id: "bajajnagar",
    name: "Bajaj Nagar",
    nameMr: "बजाजनगर",
    lat: 21.139,
    lng: 79.054,
    zone: "West",
    risk: 0.71,
    predicted: { t30: 0.74, t60: 0.69, t120: 0.64 },
    confidence: 0.86,
    manned: false,
    officersAssigned: 0,
    recommendedOfficers: 2,
    blackspot: true,
    signalized: true,
    hasCamera: true,
    waterlogged: true,
    density: 99,
    violations: { noHelmet: 31, tripleRide: 14, wrongWay: 10, redLight: 12, illegalPark: 8 },
    signal: { currentDelay: 41, recommendedDelay: 24, currentSplit: 0.5, recommendedSplit: 0.38 },
    factors: [
      { label: "Waterlogging detected (CV)", weight: 0.26, tone: "info" },
      { label: "Unmanned blackspot", weight: 0.23, tone: "danger" },
      { label: "High 2W density", weight: 0.19, tone: "warn" },
      { label: "Reduced tyre grip", weight: 0.17, tone: "info" },
      { label: "School proximity", weight: 0.15, tone: "neutral" },
    ],
  },
  {
    id: "gandhinagar",
    name: "Gandhinagar RTO",
    nameMr: "गांधीनगर आरटीओ",
    lat: 21.16,
    lng: 79.068,
    zone: "North",
    risk: 0.63,
    predicted: { t30: 0.65, t60: 0.6, t120: 0.55 },
    confidence: 0.84,
    manned: true,
    officersAssigned: 1,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: true,
    hasCamera: true,
    waterlogged: false,
    density: 81,
    violations: { noHelmet: 24, tripleRide: 9, wrongWay: 7, redLight: 8, illegalPark: 15 },
    signal: { currentDelay: 36, recommendedDelay: 23, currentSplit: 0.5, recommendedSplit: 0.4 },
    factors: [
      { label: "RTO document-check queue", weight: 0.22, tone: "warn" },
      { label: "Heavy vehicle mix", weight: 0.19, tone: "warn" },
      { label: "Signal timing sub-optimal", weight: 0.16, tone: "info" },
      { label: "Manned", weight: 0.13, tone: "good" },
      { label: "Clear lanes", weight: 0.12, tone: "good" },
    ],
  },
  {
    id: "gaddigodam",
    name: "Gaddigodam",
    nameMr: "गड्डीगोदाम",
    lat: 21.166,
    lng: 79.084,
    zone: "North",
    risk: 0.68,
    predicted: { t30: 0.7, t60: 0.66, t120: 0.61 },
    confidence: 0.84,
    manned: false,
    officersAssigned: 0,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: true,
    hasCamera: false,
    waterlogged: false,
    density: 88,
    violations: { noHelmet: 27, tripleRide: 11, wrongWay: 13, redLight: 7, illegalPark: 12 },
    signal: { currentDelay: 38, recommendedDelay: 24, currentSplit: 0.5, recommendedSplit: 0.39 },
    factors: [
      { label: "Industrial truck flow", weight: 0.23, tone: "warn" },
      { label: "Camera coverage gap", weight: 0.2, tone: "warn" },
      { label: "Unmanned", weight: 0.19, tone: "danger" },
      { label: "Narrow carriageway", weight: 0.17, tone: "neutral" },
      { label: "Poor night lighting", weight: 0.14, tone: "info" },
    ],
  },
  {
    id: "wardhaman",
    name: "Wardhaman Nagar",
    nameMr: "वर्धमान नगर",
    lat: 21.175,
    lng: 79.092,
    zone: "North",
    risk: 0.42,
    predicted: { t30: 0.44, t60: 0.4, t120: 0.38 },
    confidence: 0.79,
    manned: true,
    officersAssigned: 1,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: true,
    hasCamera: true,
    waterlogged: false,
    density: 61,
    violations: { noHelmet: 14, tripleRide: 4, wrongWay: 3, redLight: 5, illegalPark: 7 },
    signal: { currentDelay: 27, recommendedDelay: 18, currentSplit: 0.5, recommendedSplit: 0.47 },
    factors: [
      { label: "Residential calm flow", weight: 0.2, tone: "good" },
      { label: "Manned", weight: 0.16, tone: "good" },
      { label: "Good lane marking", weight: 0.15, tone: "good" },
      { label: "Minor peak congestion", weight: 0.14, tone: "neutral" },
      { label: "Well-lit", weight: 0.12, tone: "good" },
    ],
  },
  {
    id: "nandanvan",
    name: "Nandanvan",
    nameMr: "नंदनवन",
    lat: 21.17,
    lng: 79.114,
    zone: "East",
    risk: 0.66,
    predicted: { t30: 0.69, t60: 0.64, t120: 0.59 },
    confidence: 0.83,
    manned: false,
    officersAssigned: 0,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: true,
    hasCamera: true,
    waterlogged: false,
    density: 84,
    violations: { noHelmet: 26, tripleRide: 13, wrongWay: 9, redLight: 6, illegalPark: 14 },
    signal: { currentDelay: 37, recommendedDelay: 23, currentSplit: 0.5, recommendedSplit: 0.4 },
    factors: [
      { label: "Triple-riding clusters", weight: 0.23, tone: "danger" },
      { label: "Unmanned", weight: 0.21, tone: "danger" },
      { label: "Market overflow parking", weight: 0.18, tone: "warn" },
      { label: "Mixed traffic weave", weight: 0.15, tone: "neutral" },
      { label: "Signal fixed timing", weight: 0.13, tone: "info" },
    ],
  },
  {
    id: "sakkardara",
    name: "Sakkardara",
    nameMr: "सक्करदरा",
    lat: 21.135,
    lng: 79.108,
    zone: "East",
    risk: 0.73,
    predicted: { t30: 0.76, t60: 0.71, t120: 0.65 },
    confidence: 0.86,
    manned: false,
    officersAssigned: 0,
    recommendedOfficers: 2,
    blackspot: true,
    signalized: true,
    hasCamera: true,
    waterlogged: true,
    density: 95,
    violations: { noHelmet: 30, tripleRide: 15, wrongWay: 11, redLight: 13, illegalPark: 10 },
    signal: { currentDelay: 42, recommendedDelay: 25, currentSplit: 0.5, recommendedSplit: 0.37 },
    factors: [
      { label: "Waterlogging (low-lying)", weight: 0.25, tone: "info" },
      { label: "Unmanned blackspot", weight: 0.22, tone: "danger" },
      { label: "Wrong-way entry", weight: 0.19, tone: "danger" },
      { label: "Rain reduced visibility", weight: 0.17, tone: "info" },
      { label: "High 2W density", weight: 0.17, tone: "warn" },
    ],
  },
  {
    id: "panchpaoli",
    name: "Panchpaoli",
    nameMr: "पंचपावली",
    lat: 21.162,
    lng: 79.09,
    zone: "North",
    risk: 0.61,
    predicted: { t30: 0.63, t60: 0.59, t120: 0.54 },
    confidence: 0.83,
    manned: true,
    officersAssigned: 1,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: true,
    hasCamera: false,
    waterlogged: false,
    density: 79,
    violations: { noHelmet: 23, tripleRide: 10, wrongWay: 8, redLight: 7, illegalPark: 12 },
    signal: { currentDelay: 35, recommendedDelay: 22, currentSplit: 0.5, recommendedSplit: 0.41 },
    factors: [
      { label: "Camera coverage gap", weight: 0.21, tone: "warn" },
      { label: "Pedestrian crossings", weight: 0.18, tone: "warn" },
      { label: "Auto-rickshaw queuing", weight: 0.16, tone: "neutral" },
      { label: "Manned", weight: 0.13, tone: "good" },
      { label: "Acceptable flow", weight: 0.12, tone: "good" },
    ],
  },
  {
    id: "itwari",
    name: "Itwari Market",
    nameMr: "इटवरी बाजार",
    lat: 21.156,
    lng: 79.098,
    zone: "East",
    risk: 0.84,
    predicted: { t30: 0.86, t60: 0.81, t120: 0.75 },
    confidence: 0.91,
    manned: true,
    officersAssigned: 1,
    recommendedOfficers: 3,
    blackspot: true,
    signalized: true,
    hasCamera: true,
    waterlogged: false,
    density: 151,
    violations: { noHelmet: 44, tripleRide: 28, wrongWay: 16, redLight: 20, illegalPark: 35 },
    signal: { currentDelay: 52, recommendedDelay: 28, currentSplit: 0.5, recommendedSplit: 0.33 },
    factors: [
      { label: "Wholesale-market density", weight: 0.27, tone: "danger" },
      { label: "Triple-riding 28%", weight: 0.22, tone: "danger" },
      { label: "Handcart–2W conflict", weight: 0.19, tone: "warn" },
      { label: "Severely under-staffed (1 of 3)", weight: 0.18, tone: "danger" },
      { label: "Loading-zone spill", weight: 0.14, tone: "warn" },
    ],
  },
  {
    id: "mahal",
    name: "Mahal (Ghatkaranja)",
    nameMr: "महाल",
    lat: 21.157,
    lng: 79.093,
    zone: "Central",
    risk: 0.69,
    predicted: { t30: 0.71, t60: 0.67, t120: 0.62 },
    confidence: 0.84,
    manned: false,
    officersAssigned: 0,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: false,
    hasCamera: true,
    waterlogged: false,
    density: 92,
    violations: { noHelmet: 28, tripleRide: 12, wrongWay: 14, redLight: 0, illegalPark: 18 },
    signal: { currentDelay: 47, recommendedDelay: 30, currentSplit: 0.5, recommendedSplit: 0.5 },
    factors: [
      { label: "Unsignalised junction", weight: 0.24, tone: "warn" },
      { label: "Heritage-zone pedestrian mix", weight: 0.2, tone: "warn" },
      { label: "Unmanned", weight: 0.19, tone: "danger" },
      { label: "Narrow heritage roads", weight: 0.17, tone: "neutral" },
      { label: "Tourist footfall", weight: 0.13, tone: "neutral" },
    ],
  },
  {
    id: "manishnagar",
    name: "Manish Nagar",
    nameMr: "मनीष नगर",
    lat: 21.106,
    lng: 79.056,
    zone: "South-West",
    risk: 0.51,
    predicted: { t30: 0.53, t60: 0.49, t120: 0.46 },
    confidence: 0.81,
    manned: true,
    officersAssigned: 1,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: true,
    hasCamera: true,
    waterlogged: false,
    density: 66,
    violations: { noHelmet: 17, tripleRide: 6, wrongWay: 4, redLight: 5, illegalPark: 9 },
    signal: { currentDelay: 29, recommendedDelay: 20, currentSplit: 0.5, recommendedSplit: 0.45 },
    factors: [
      { label: "Residential-mixed flow", weight: 0.19, tone: "neutral" },
      { label: "Manned", weight: 0.16, tone: "good" },
      { label: "School AM peak", weight: 0.15, tone: "warn" },
      { label: "Signal adequate", weight: 0.13, tone: "good" },
      { label: "Low conflict", weight: 0.12, tone: "good" },
    ],
  },
  {
    id: "koradi",
    name: "Koradi Naka",
    nameMr: "कोराडी नाका",
    lat: 21.215,
    lng: 79.098,
    zone: "North",
    risk: 0.57,
    predicted: { t30: 0.59, t60: 0.55, t120: 0.51 },
    confidence: 0.82,
    manned: false,
    officersAssigned: 0,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: true,
    hasCamera: false,
    waterlogged: false,
    density: 77,
    violations: { noHelmet: 21, tripleRide: 7, wrongWay: 6, redLight: 8, illegalPark: 6 },
    signal: { currentDelay: 33, recommendedDelay: 22, currentSplit: 0.5, recommendedSplit: 0.43 },
    factors: [
      { label: "Highway merge speed variance", weight: 0.23, tone: "warn" },
      { label: "Camera coverage gap", weight: 0.2, tone: "warn" },
      { label: "Unmanned", weight: 0.18, tone: "danger" },
      { label: "Heavy-vehicle share", weight: 0.16, tone: "neutral" },
      { label: "Open visibility", weight: 0.12, tone: "good" },
    ],
  },
  {
    id: "khapri",
    name: "Khapri (MIHAN gate)",
    nameMr: "खापरी",
    lat: 21.19,
    lng: 79.033,
    zone: "South-West",
    risk: 0.45,
    predicted: { t30: 0.47, t60: 0.43, t120: 0.41 },
    confidence: 0.8,
    manned: true,
    officersAssigned: 1,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: true,
    hasCamera: true,
    waterlogged: false,
    density: 58,
    violations: { noHelmet: 13, tripleRide: 3, wrongWay: 2, redLight: 4, illegalPark: 5 },
    signal: { currentDelay: 26, recommendedDelay: 18, currentSplit: 0.5, recommendedSplit: 0.47 },
    factors: [
      { label: "Industrial-logistics flow", weight: 0.19, tone: "neutral" },
      { label: "Wide carriageway", weight: 0.16, tone: "good" },
      { label: "Manned", weight: 0.15, tone: "good" },
      { label: "Camera coverage good", weight: 0.13, tone: "good" },
      { label: "Low conflict", weight: 0.12, tone: "good" },
    ],
  },
  {
    id: "zeromile",
    name: "Zero Mile",
    nameMr: "झिरो माईल",
    lat: 21.1518,
    lng: 79.0822,
    zone: "Central",
    risk: 0.64,
    predicted: { t30: 0.66, t60: 0.62, t120: 0.57 },
    confidence: 0.85,
    manned: false,
    officersAssigned: 0,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: true,
    hasCamera: true,
    waterlogged: false,
    density: 83,
    violations: { noHelmet: 25, tripleRide: 9, wrongWay: 7, redLight: 10, illegalPark: 11 },
    signal: { currentDelay: 36, recommendedDelay: 23, currentSplit: 0.5, recommendedSplit: 0.4 },
    factors: [
      { label: "Tourist-monument footfall", weight: 0.21, tone: "warn" },
      { label: "Unmanned", weight: 0.19, tone: "danger" },
      { label: "Central convergence", weight: 0.18, tone: "neutral" },
      { label: "Signal fixed timing", weight: 0.15, tone: "info" },
      { label: "Good visibility", weight: 0.12, tone: "good" },
    ],
  },
  {
    id: "bardi",
    name: "Bardi",
    nameMr: "बरडी",
    lat: 21.13,
    lng: 79.094,
    zone: "East",
    risk: 0.49,
    predicted: { t30: 0.51, t60: 0.47, t120: 0.44 },
    confidence: 0.8,
    manned: true,
    officersAssigned: 1,
    recommendedOfficers: 1,
    blackspot: false,
    signalized: true,
    hasCamera: false,
    waterlogged: false,
    density: 63,
    violations: { noHelmet: 15, tripleRide: 5, wrongWay: 4, redLight: 4, illegalPark: 8 },
    signal: { currentDelay: 28, recommendedDelay: 19, currentSplit: 0.5, recommendedSplit: 0.46 },
    factors: [
      { label: "Camera coverage gap", weight: 0.2, tone: "warn" },
      { label: "Manned", weight: 0.16, tone: "good" },
      { label: "Residential flow", weight: 0.15, tone: "good" },
      { label: "Minor parking", weight: 0.13, tone: "neutral" },
      { label: "Low conflict", weight: 0.12, tone: "good" },
    ],
  },
  {
    id: "HINGNA",
    name: "Hingna T-Point",
    nameMr: "हिंगणा",
    lat: 21.09,
    lng: 79.03,
    zone: "South-West",
    risk: 0.72,
    predicted: { t30: 0.74, t60: 0.7, t120: 0.64 },
    confidence: 0.85,
    manned: false,
    officersAssigned: 0,
    recommendedOfficers: 2,
    blackspot: true,
    signalized: true,
    hasCamera: true,
    waterlogged: false,
    density: 101,
    violations: { noHelmet: 32, tripleRide: 13, wrongWay: 12, redLight: 11, illegalPark: 9 },
    signal: { currentDelay: 43, recommendedDelay: 25, currentSplit: 0.5, recommendedSplit: 0.37 },
    factors: [
      { label: "Heavy-truck T-junction", weight: 0.24, tone: "danger" },
      { label: "Unmanned blackspot", weight: 0.22, tone: "danger" },
      { label: "High speed variance", weight: 0.19, tone: "warn" },
      { label: "Industrial worker flow", weight: 0.16, tone: "neutral" },
      { label: "Poor lighting", weight: 0.13, tone: "info" },
    ],
  },
];

export function getJunction(id: string): Junction | undefined {
  return JUNCTIONS.find((j) => j.id === id);
}

export const OFFICERS: Officer[] = [
  { id: "o1", name: "A. Deshmukh", badge: "TP-1042", status: "deployed", post: "Variety Square" },
  { id: "o2", name: "R. Pawar", badge: "TP-1108", status: "deployed", post: "Medical Square" },
  { id: "o3", name: "S. Khaire", badge: "TP-1203", status: "deployed", post: "Ajni Square" },
  { id: "o4", name: "M. Joshi", badge: "TP-1311", status: "deployed", post: "Dharampeth" },
  { id: "o5", name: "P. Shende", badge: "TP-1422", status: "available", post: null },
  { id: "o6", name: "N. Bhoyar", badge: "TP-1509", status: "available", post: null },
  { id: "o7", name: "K. Rathod", badge: "TP-1617", status: "available", post: null },
  { id: "o8", name: "T. Choudhary", badge: "TP-1730", status: "break", post: null },
  { id: "o9", name: "V. More", badge: "TP-1844", status: "available", post: null },
  { id: "o10", name: "G. Ingle", badge: "TP-1902", status: "available", post: null },
  { id: "o11", name: "D. Wankhede", badge: "TP-2015", status: "available", post: null },
  { id: "o12", name: "H. Suryawanshi", badge: "TP-2128", status: "available", post: null },
];

export const FESTIVAL_EVENTS: FestivalEvent[] = [
  {
    id: "deekshabhoomi",
    name: "Deekshabhoomi Gathering",
    nameMr: "दीक्षाभूमी",
    zone: "Central",
    date: "Active today · 16:00–22:00",
    officers: 10,
    active: false,
    playbook: [
      "10 officers at Deekshabhoomi perimeter",
      "5 officers at surrounding junctions (Sitabuldi, Variety, Medical)",
      "Barricade分流 at entry arms",
      "Ambulance standby lane reserved",
    ],
  },
  {
    id: "visarjan",
    name: "Ganesh Visarjan Route",
    nameMr: "गणेश विसर्जन",
    zone: "Central–East",
    date: "Scheduled · evening route",
    officers: 14,
    active: false,
    playbook: [
      "14 officers along Visarjan corridor",
      "Rolling roadblocks ahead of processions",
      "Traffic hold at Futala lake approach",
      "Crowd density CV watch on Itwari route",
    ],
  },
  {
    id: "marathon",
    name: "Nagpur Marathon",
    nameMr: "नागपूर मॅरेथॉन",
    zone: "Multi-zone",
    date: "Scheduled · Sunday 06:00",
    officers: 22,
    active: false,
    playbook: [
      "22 officers across race route",
      "Lead & sweep vehicles",
      "Cross-traffic holds at 9 junctions",
      "Hydration-zone diversions",
    ],
  },
];

export const WEATHER = {
  condition: "Light Rain",
  tempC: 26,
  humidity: 88,
  visibility: "Moderate · 1.4 km",
  rainMm: 6.2,
  icon: "rain",
};

export const BASELINE_METRICS = {
  highRiskCoverage: 0.34,
  responseTimeMin: 11.4,
  utilization: 0.58,
  avgDelay: 38,
  unmannedBlackspots: 9,
  predictedIncidents: 23,
};

export const RECOMMENDED_METRICS = {
  highRiskCoverage: 0.72,
  responseTimeMin: 6.8,
  utilization: 0.81,
  avgDelay: 25,
  unmannedBlackspots: 4,
  predictedIncidents: 13,
};

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: "inc-seed-1",
    type: "waterlogging",
    junctionId: "bajajnagar",
    junctionName: "Bajaj Nagar",
    severity: "high",
    status: "active",
    time: "14 min ago",
    note: "CV waterlogging detection on south arm — slippery surface, 2W skid risk.",
  },
];

export const INITIAL_AUDIT: AuditEntry[] = [
  {
    id: "a1",
    time: "10:42",
    user: "Insp. R. Pawar",
    action: "Accepted recommendation",
    target: "Itwari Market (+2 officers)",
    reason: "Market density + triple-riding confirmed via feed",
    impact: "High-risk coverage +6%",
  },
  {
    id: "a2",
    time: "10:28",
    user: "DCP Traffic",
    action: "Manual override",
    target: "Sakkardara deployment",
    reason: "Local festival crowd anticipated; officer doubled",
    impact: "Utilization +4%",
  },
];

/** Major Nagpur road segments connecting junctions, with traffic status derived from adjacent junction risk/density. */
export interface RoadSegment {
  id: string;
  name: string;
  /** Ordered lat/lng pairs forming the road polyline */
  path: [number, number][];
  /** 'light' | 'moderate' | 'heavy' — derived from avg risk of adjacent junctions */
  traffic: 'light' | 'moderate' | 'heavy';
  /** Whether this road is prone to waterlogging when rain > 5mm */
  floodProne: boolean;
  /** Average risk score of adjacent junctions (0-1) */
  avgRisk: number;
}

export const ROAD_SEGMENTS: RoadSegment[] = [
  // ── Central Nagpur Corridors ──
  {
    id: 'sitabuldi-variety',
    name: 'Sitabuldi Rd (Main Spine)',
    path: [[21.1496, 79.086], [21.1475, 79.0855], [21.1455, 79.0851]],
    traffic: 'heavy',
    floodProne: false,
    avgRisk: 0.85,
  },
  {
    id: 'variety-lic',
    name: 'Central Avenue',
    path: [[21.1455, 79.0851], [21.149, 79.081], [21.152, 79.079]],
    traffic: 'heavy',
    floodProne: false,
    avgRisk: 0.79,
  },
  {
    id: 'lic-medical',
    name: 'Wardha Rd (Central)',
    path: [[21.152, 79.079], [21.1512, 79.076], [21.1505, 79.073]],
    traffic: 'heavy',
    floodProne: false,
    avgRisk: 0.775,
  },
  {
    id: 'sitabuldi-zeromile',
    name: 'Kingsway (Station Link)',
    path: [[21.1496, 79.086], [21.1507, 79.084], [21.1518, 79.0822]],
    traffic: 'moderate',
    floodProne: false,
    avgRisk: 0.76,
  },
  {
    id: 'zeromile-mahal',
    name: 'Mahal Heritage Rd',
    path: [[21.1518, 79.0822], [21.154, 79.087], [21.157, 79.093]],
    traffic: 'moderate',
    floodProne: false,
    avgRisk: 0.665,
  },
  {
    id: 'dharampeth-ramdaspeth',
    name: 'West High Court Rd (WHC)',
    path: [[21.147, 79.078], [21.1445, 79.0785], [21.142, 79.079]],
    traffic: 'light',
    floodProne: false,
    avgRisk: 0.505,
  },
  {
    id: 'ramdaspeth-medical',
    name: 'Ramdaspeth – Medical Link',
    path: [[21.142, 79.079], [21.146, 79.076], [21.1505, 79.073]],
    traffic: 'moderate',
    floodProne: false,
    avgRisk: 0.665,
  },

  // ── West & South-West Corridors ──
  {
    id: 'medical-ajni',
    name: 'Wardha Rd (Airport Direction)',
    path: [[21.1505, 79.073], [21.145, 79.07], [21.139, 79.067]],
    traffic: 'moderate',
    floodProne: false,
    avgRisk: 0.685,
  },
  {
    id: 'ajni-bajajnagar',
    name: 'Inner Ring Road (SW)',
    path: [[21.139, 79.067], [21.139, 79.06], [21.139, 79.054]],
    traffic: 'heavy',
    floodProne: true,
    avgRisk: 0.645,
  },
  {
    id: 'bajajnagar-manishnagar',
    name: 'Wardha Rd (South Corridor)',
    path: [[21.139, 79.054], [21.12, 79.055], [21.106, 79.056]],
    traffic: 'moderate',
    floodProne: false,
    avgRisk: 0.61,
  },
  {
    id: 'manishnagar-hingna',
    name: 'Hingna Industrial Road',
    path: [[21.106, 79.056], [21.098, 79.043], [21.09, 79.03]],
    traffic: 'heavy',
    floodProne: false,
    avgRisk: 0.615,
  },
  {
    id: 'manishnagar-khapri',
    name: 'MIHAN Express Link',
    path: [[21.106, 79.056], [21.145, 79.045], [21.19, 79.033]],
    traffic: 'light',
    floodProne: false,
    avgRisk: 0.48,
  },

  // ── East Nagpur Corridors ──
  {
    id: 'mahal-itwari',
    name: 'Itwari Wholesale Market Rd',
    path: [[21.157, 79.093], [21.1565, 79.0955], [21.156, 79.098]],
    traffic: 'heavy',
    floodProne: false,
    avgRisk: 0.765,
  },
  {
    id: 'itwari-nandanvan',
    name: 'Kamptee Rd (East Spine)',
    path: [[21.156, 79.098], [21.163, 79.106], [21.17, 79.114]],
    traffic: 'heavy',
    floodProne: false,
    avgRisk: 0.75,
  },
  {
    id: 'itwari-sakkardara',
    name: 'Sakkardara Lake Bypass',
    path: [[21.156, 79.098], [21.146, 79.103], [21.135, 79.108]],
    traffic: 'heavy',
    floodProne: true,
    avgRisk: 0.785,
  },
  {
    id: 'sakkardara-bardi',
    name: 'Bardi – Reshimbagh Rd',
    path: [[21.135, 79.108], [21.133, 79.101], [21.13, 79.094]],
    traffic: 'light',
    floodProne: false,
    avgRisk: 0.61,
  },

  // ── North Nagpur Corridors ──
  {
    id: 'panchpaoli-gaddigodam',
    name: 'Amravati – Gaddigodam Rd',
    path: [[21.162, 79.09], [21.164, 79.087], [21.166, 79.084]],
    traffic: 'moderate',
    floodProne: false,
    avgRisk: 0.645,
  },
  {
    id: 'gaddigodam-wardhaman',
    name: 'Kamptee Rd (North)',
    path: [[21.166, 79.084], [21.17, 79.088], [21.175, 79.092]],
    traffic: 'light',
    floodProne: false,
    avgRisk: 0.55,
  },
  {
    id: 'wardhaman-koradi',
    name: 'Koradi Highway (Four Lane)',
    path: [[21.175, 79.092], [21.19, 79.095], [21.215, 79.098]],
    traffic: 'light',
    floodProne: false,
    avgRisk: 0.495,
  },
  {
    id: 'gandhinagar-panchpaoli',
    name: 'North Ring Road',
    path: [[21.16, 79.068], [21.161, 79.079], [21.162, 79.09]],
    traffic: 'moderate',
    floodProne: false,
    avgRisk: 0.62,
  },
  {
    id: 'gandhinagar-gaddigodam',
    name: 'Great Nag Road',
    path: [[21.16, 79.068], [21.163, 79.076], [21.166, 79.084]],
    traffic: 'moderate',
    floodProne: false,
    avgRisk: 0.655,
  },
];

/** Nagpur roads known to waterlog during monsoon (rainfall > threshold). */
export const WATERLOG_ROADS = ROAD_SEGMENTS.filter((r) => r.floodProne);

/** Rainfall threshold (mm) above which flood-prone roads get waterlogging warnings. */
export const WATERLOG_THRESHOLD_MM = 5;

/** Great-circle distance calculation between two coordinates in kilometers. */
export function getDistanceKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371; // Radius of Earth in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

/** Returns the closest road segment to a given user coordinate. */
export function getClosestRoad(userLat: number, userLng: number): { road: RoadSegment; distanceKm: number } {
  let closest = ROAD_SEGMENTS[0];
  let minD = Infinity;

  for (const road of ROAD_SEGMENTS) {
    // Check distance to mid-point and start/end points
    for (const pt of road.path) {
      const d = getDistanceKm(userLat, userLng, pt[0], pt[1]);
      if (d < minD) {
        minD = d;
        closest = road;
      }
    }
  }

  return { road: closest, distanceKm: minD };
}


